INSERT INTO products (name, description, price, imagename) VALUES ('Fussball', 'FC Barcelona Fussball. Viertes Kit Stil', 27.99, 'Ball.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Barca 4th Kit', 'FC Barcelona 4tes Shirt ', 94.99, 'BarcaFourth.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Basketball', 'FC Barcelona Basketball', 24.99, 'Basketball.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Barcelona Flasche', 'Getränkeflasche im FC Barcelona Stil ', 14.99, 'Bottle.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Captain Armband', 'FC Barcelona Club Capitän Armband', 19.99, 'Captain_Armband.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Cruyff Polo', 'Barca Exclusive Cruyff Polo', 64.99, 'Cruyff_Polo.png');
INSERT INTO products (name, description, price, imagename) VALUES ('1984-1989 Home Kit', 'FC Barcelona Home Kit von 1984 bis 1989', 69.99, 'HomeKit.png');
INSERT INTO products (name, description, price, imagename) VALUES ('My first Barcelona', 'My first Barcelona Buch für Kinder', 12.95, 'MiPrimerBarca.png');
INSERT INTO products (name, description, price, imagename) VALUES ('Rosalia Home Shirt', 'Rosalia Limited Shirt 1 von 1899', 399.99, 'Rosalia_Shirt.png');
INSERT INTO products (name, description, price, imagename) VALUES ('FC Barcelona Socken', 'FC Barcelona Socken im 3. Kit Stil', 17.99, 'Socks.png');
